### PR TITLE
adopt package.json to support coffee-script 1.9.0. 

### LINKED ISSUE #17: Support for Coffe-Script 1.9
currently only coffee 1.8 is supported.

### PR DESCRIPTION
**Pull request by amitevski**
I want to resolve #17. According to http://coffeescript.org/#changelog no bigger changes have been made..

### CODE REVIEW

**Comment by obweger** [comment]
cs 1.9.1 already released

**Comment by bcherny** [comment]
+1 please merge this in, but use `>= 1.6 <= 1.9.x` instead of `>= 1.6 <= 1.9.0`

**Comment by rodw** [comment]
For what it is worth I've used a variation on this patch to publish a version of coffee-jshint that is configured to work with CoffeeScript 1.9.x on npm as coffee-19-jshint, with a GitHub repository at rodw/coffee-jshint.

To install it, use `npm install coffee-19-jshint -g`, etc.

Otherwise it should work exactly the same as the original coffee-jshint.

I'd be more than happy to remove my fork, or at least abandon it, once Clever/coffee-jshint is updated to allow CoffeeScript 1.9.

**Comment by alexhancock** [comment]
Status on this?

**Comment by jonahkagan** [comment]
@rodw would you like to make a PR with your variation on this patch? I can see about getting it merged in once you do.

**Comment by cueedee** [comment]
@jonahkagan, given the prolongued period of inactivity here (@rodw, where are you?). Would you mind If I prepared such a PR instead?

If so,  would you mind if I relieved the restriction on the `coffee-script` peer-dependency version range to, say, any version below `2`? (that is: `>= 1.6 < 2`). I am tempted even to remove that upper bound altogether but I do not know wether there are compelling reasons to be more restrictive. (I wondered about this earlier in [#17](/Clever/coffee-jshint/issues/17#issuecomment-117846063)).

**Comment by jonahkagan** [comment]
@cueedee it would be great if you could make that PR. Seems reasonable to make a less restrictive range. I'm hesitant to remove the upper bound completely since a major version bump to the language could have behavior-breaking consequences for coffee-jshint.

**Comment by rodw** [comment]
Hey @jonahkagan and @cueedee, sorry for the delay.  I've been crazy busy of the past couple of weeks.  

My fork has several other changes that support publishing it on npm as a different module, but the only changes of interest are to these two properties in package.json:

 "peerDependencies": {
-    "coffee-script": ">= 1.6 <= 1.9"
+    "coffee-script": ">= 1.6 <= 2"
   },

   "devDependencies": {
-    "coffee-script": "~1.6.0"
+    "coffee-script": "1.9.x"
   },

I.e., the completed file should include:

    "peerDependencies": {
        "coffee-script": ">= 1.6 <= 2"
     }

and

     "devDependencies": {
         "coffee-script": "1.9.x"
     }

Actually, upon review the peerDependencies part should probably be:

    "peerDependencies": {
        "coffee-script": ">= 1.6 < 2"
     }

to exclude 2.0.0 for now.

@cueedee and/or @jonahkagan  - feel to create the pull request and/or just make the changes directly; I won't be offended in the least.

**Comment by cueedee** [comment]
I'll get right on it.

**Comment by cueedee** [comment]
[Done](/Clever/coffee-jshint/pull/23).

**Comment by jonahkagan** [comment]
closing in favor of #23

**Pull request closed without merging**
